import type { DecisionCenterPlayer, DecisionCenterResponse } from "./types";

function player(
  elementId: number,
  name: string,
  webName: string,
  team: string,
  teamCode: number,
  position: string,
  price: number,
  expectedPoints: number,
): DecisionCenterPlayer {
  return {
    element_id: elementId,
    name,
    web_name: webName,
    team,
    team_code: teamCode,
    position,
    price,
    expected_points: expectedPoints,
    start_likelihood: 1,
    blank: false,
    double: false,
  };
}

const demoPlayers = {
  tzolakis: player(572, "Tzolakis", "Tzolakis", "Hull City", 88, "GKP", 4.7, 4.4),
  verbruggen: player(109, "Verbruggen", "Verbruggen", "Brighton", 36, "GKP", 4.5, 4.0),
  tarkowski: player(229, "Tarkowski", "Tarkowski", "Everton", 11, "DEF", 6.2, 4.7),
  bogle: player(330, "Bogle", "Bogle", "Leeds", 2, "DEF", 4.6, 4.6),
  gvardiol: player(391, "Gvardiol", "Gvardiol", "Man City", 43, "DEF", 5.7, 4.8),
  hall: player(449, "Hall", "Hall", "Newcastle", 4, "DEF", 5.3, 4.1),
  mykolenko: player(233, "Mykolenko", "Mykolenko", "Everton", 11, "DEF", 4.6, 3.8),
  gross: player(124, "Groß", "Groß", "Brighton", 36, "MID", 5.8, 6.2),
  schade: player(94, "Schade", "Schade", "Brentford", 94, "MID", 6.2, 5.7),
  cherki: player(399, "Cherki", "Cherki", "Man City", 43, "MID", 7.8, 5.4),
  saka: player(12, "Saka", "Saka", "Arsenal", 3, "MID", 9.5, 6.3),
  dowell: player(288, "Dowell", "Dowell", "Hull City", 88, "MID", 4.5, 1.4),
  tavernier: player(68, "Tavernier", "Tavernier", "Bournemouth", 91, "MID", 6.1, 5.8),
  haaland: player(411, "Haaland", "Haaland", "Man City", 43, "FWD", 15.6, 8.8),
  joaoPedro: player(165, "João Pedro", "João Pedro", "Chelsea", 8, "FWD", 7.7, 5.5),
  kostoulas: player(138, "Kostoulas", "Kostoulas", "Brighton", 36, "FWD", 5.6, 5.0),
};

const currentStarters = [
  demoPlayers.tzolakis,
  demoPlayers.tarkowski,
  demoPlayers.bogle,
  demoPlayers.gvardiol,
  demoPlayers.dowell,
  demoPlayers.schade,
  demoPlayers.cherki,
  demoPlayers.saka,
  demoPlayers.haaland,
  demoPlayers.joaoPedro,
  demoPlayers.kostoulas,
];

const currentBench = [
  demoPlayers.gross,
  demoPlayers.hall,
  demoPlayers.mykolenko,
  demoPlayers.verbruggen,
];

const recommendedStarters = [
  demoPlayers.tzolakis,
  demoPlayers.tarkowski,
  demoPlayers.bogle,
  demoPlayers.gvardiol,
  demoPlayers.gross,
  demoPlayers.schade,
  demoPlayers.cherki,
  demoPlayers.saka,
  demoPlayers.tavernier,
  demoPlayers.haaland,
  demoPlayers.joaoPedro,
];

const recommendedBench = [
  demoPlayers.kostoulas,
  demoPlayers.hall,
  demoPlayers.mykolenko,
  demoPlayers.verbruggen,
];

export function createDemoDecisionCenter(gameweek: number): DecisionCenterResponse {
  const transfer = {
    outgoing_id: demoPlayers.dowell.element_id,
    outgoing_name: demoPlayers.dowell.web_name ?? demoPlayers.dowell.name,
    incoming_id: demoPlayers.tavernier.element_id,
    incoming_name: demoPlayers.tavernier.web_name ?? demoPlayers.tavernier.name,
    projected_gain: 4.8,
    hit_cost: 0,
    outgoing_price: demoPlayers.dowell.price,
    incoming_price: demoPlayers.tavernier.price,
    bank_effect: -1.6,
  };

  return {
    status: "ready",
    message: "Illustrative guest decision using a dedicated sample squad.",
    team_id: null,
    season_state: "in_season",
    gameweek,
    horizon: 3,
    rules_version: "2026-27-demo",
    transfer_model: "SquadMetric demo projection",
    captain_model: "SquadMetric demo projection",
    chip_model: null,
    rating: {
      grade: "C+",
      score: 68,
      after_grade: "B",
      after_score: 77,
      horizon: 3,
      projected_points: 166.2,
      recommended_projected_points: 171,
      benchmark_points: 178.6,
      gap_to_best: 12.4,
      budget: 100,
      provisional: false,
      summary: "This sample squad has a strong core, but one low-impact midfield slot and an inefficient submitted lineup leave clear room to improve.",
      factors: [
        { label: "Projected strength", status: "improvable", detail: "166.2 projected points over the next 3 gameweeks." },
        { label: "Lineup efficiency", status: "warning", detail: "A high-upside midfielder is currently on the bench." },
        { label: "Transfer opportunity", status: "strong", detail: "One free transfer produces a meaningful projected gain." },
      ],
      method: "Demo grades use the same three-gameweek structure as personalized ratings, with a fixed sample squad so every guest sees a clear example.",
    },
    state_before: {
      bank: 1.7,
      free_transfers: 1,
      remaining_chips: ["wildcard", "freehit", "triplecaptain", "bboost"],
      used_chips: [],
    },
    current_lineup: {
      starting_xi: currentStarters,
      bench_order: currentBench,
      captain_id: demoPlayers.haaland.element_id,
      vice_captain_id: demoPlayers.saka.element_id,
    },
    recommendation: {
      transfer_action: "make_1_transfer",
      transfers: [transfer],
      transfer_count: 1,
      hit_recommended: false,
      hit_cost: 0,
      bank_before: 1.7,
      bank_after: 0.1,
      free_transfers_after: 1,
      funds_released: 0,
      funds_spent: 1.6,
      funding_explanation: "Use £1.6m from the bank to turn a low-impact midfield slot into a stronger three-gameweek option.",
      future_plan: [
        {
          gameweek: Math.min(38, gameweek + 1),
          transfers: [],
          transfer_count: 0,
          hit_cost: 0,
          expected_points: 57.2,
          net_expected_points: 57.2,
          bank_before: 0.1,
          bank_after: 0.1,
          free_transfers_before: 1,
          free_transfers_after: 2,
          funds_released: 0,
          funds_spent: 0,
          funding_explanation: "Recheck injuries and roll if nothing material changes.",
        },
      ],
      chip_action: "save",
      chip_key: null,
      starting_xi: recommendedStarters,
      bench_order: recommendedBench,
      captain_id: demoPlayers.haaland.element_id,
      vice_captain_id: demoPlayers.saka.element_id,
      expected_gameweek_points: 71,
      expected_horizon_points: 171,
      gain_vs_no_action: 4.8,
      future_opportunity_cost: 0.4,
      uncertainty_penalty: 0.6,
      downside_range: { low: 69.8, high: 72.2, method: "expected points plus/minus planner uncertainty adjustment" },
      confidence: "high",
      confidence_basis: { search_score_margin: 3.7, uncertainty_penalty: 0.6 },
      reason: "The upgrade adds enough projected value to justify using the free transfer while keeping a legal squad and positive bank balance.",
    },
    no_action: {
      expected_gameweek_points: 66.3,
      expected_horizon_points: 166.2,
      starting_ids: currentStarters.map((item) => item.element_id),
      captain_id: demoPlayers.haaland.element_id,
      vice_captain_id: demoPlayers.saka.element_id,
      reason: "Keep the sample squad unchanged.",
    },
    alternatives: [
      {
        branch_id: "demo-roll",
        chip: "save",
        transfers: [],
        hit_cost: 0,
        expected_gameweek_points: 66.3,
        expected_horizon_points: 166.2,
        gain_vs_no_action: 0,
        reason: "Bank the free transfer.",
      },
      {
        branch_id: "demo-belloumi",
        chip: "save",
        transfers: [{ ...transfer, incoming_id: 286, incoming_name: "Belloumi", incoming_price: 5.1, projected_gain: 3.1, bank_effect: -0.6 }],
        hit_cost: 0,
        expected_gameweek_points: 69.2,
        expected_horizon_points: 169.3,
        gain_vs_no_action: 3.1,
        reason: "A cheaper improvement that keeps more money in the bank.",
      },
    ],
  };
}
